version: "3.2"
services:
  postgres:
    restart: always
    image: postgres
    networks: 
      - app
    environment:
      POSTGRES_PASSWORD: ${JELLYFISH_DB_PASSWORD}
      POSTGRES_DB: jellyfish
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  migration:
    image: boxfuse/flyway
    networks: 
      - app
    command: -url=jdbc:postgresql://postgres:5432/jellyfish -user=postgres -password=${JELLYFISH_DB_PASSWORD} migrate
    volumes:
      - ./jellyfish/sql:/flyway/sql 
    depends_on:
      - postgres
  nginx:
    restart: always
    image: fwchen/jellyfish-web:latest
    ports:
      - "9090:80"
    networks: 
      - app
    links:
      - backend:backend
  backend:
    restart: always
    image: fwchen/jellyfish-backend:latest
    networks: 
      - app
    environment:
      JFISH_JWT_KEY: ${JELLYFISH_JWT_KEY}
      JFISH_DBNAME: jellyfish
      JFISH_DBHOST: postgres
      JFISH_DBUSER: postgres
      JFISH_DBPASSWORD: ${JELLYFISH_DB_PASSWORD}
    volumes:
      - ./upload:/app/upload
    depends_on:
      - migration
networks:
  app: